cspr-rad/kairos

flake.nix

Unless we have explicit reason to use nightly toolchain, we should stick to stable one.

Use Rust stable toolchain

---

kairos-server/src/lib.rs
kairos-server/src/routes/deposit.rs
kairos-server/src/routes/withdraw.rs

Fix for #31 - we want to rely on bytes, not strings. Additionally, using type aliases at this point has no value.

Replace `PublicKey` and `Signature` with plain `Vec<u8>`

---

kairos-cli/src/common/args.rs

`#[arg(name)] was allowed by mistake, instead use `#[arg(id)]` or `#[arg(value_name)]`
closes #37

kairos-cli: fix use of deprecated function

---

kairos-cli/Cargo.toml

There is interesting `clap`'s [optional feature](https://docs.rs/clap/latest/clap/_features/index.html#optional-features) that we should enable:
> - deprecated: Guided experience to prepare for next breaking release (at different stages of development, this may become default)
This would trigger the warnings like this reported in https://github.com/cspr-rad/kairos/issues/37:
```
warning: use of deprecated function `<common::args::AmountArg as clap::Args>::augment_args::id_is_only_for_arg`: `#[arg(name)] was allowed by mistake, instead use `#[arg(id
)]` or `#[arg(value_name)]`
```

Enable `clap` feature for reporting deprecation

---

README.md

This PR clarifies dual licensing, by adding extra **License** section to `README`.
**Briefly put:**
- Contributions are made with Apache  2.0 license (unless stated otherwise).
- Users can use this software either as MIT **or** Apache 2.0.
---
- https://internals.rust-lang.org/t/rationale-of-apache-dual-licensing/8952/4
- https://github.com/sfackler/rust-postgres-macros/issues/19
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

Clarify dual licensing

---

kairos-server/src/routes/transfer.rs
kairos-server/src/routes/withdraw.rs

This PR reduces complexity of integrating Tx format (#30) with server, by decoupling request body from handler and related helpers.

Decouple transaction body from handlers

---

Cargo.lock
kairos-server/Cargo.toml
kairos-server/src/lib.rs
kairos-server/src/routes/deposit.rs
kairos-server/src/routes/mod.rs
kairos-server/src/routes/transfer.rs
kairos-server/src/routes/withdraw.rs
kairos-server/src/state.rs
kairos-server/src/utils.rs
kairos-server/tests/transactions.rs

This PR integrates deterministic transaction format (introduced in https://github.com/cspr-rad/kairos/pull/30) - with Kairos server.
1. Error handling could be better, but blocked by #10.
2. Signature verification will be integrated once #35 is merged.

Integrate ASN.1 transaction format with server

---

kairos-server/src/routes/mod.rs
nixos/tests/end-to-end.nix

Fixes on top of #59:
- https://github.com/cspr-rad/kairos/pull/65/commits/e5193f109d55d9a233a200c8055081dae30054e7 - Handle public key as hexstring.
- https://github.com/cspr-rad/kairos/pull/65/commits/94d3af986163d6d2d1abcb0958a534b24d2d4bf3 - Update tx payload to the new format.

Fix broken e2e tests for server requests

---

.github/workflows/extra-check.yml
Cargo.lock
kairos-tx/Cargo.toml
kairos-tx/src/asn.rs
kairos-tx/src/error.rs
kairos-tx/src/helpers.rs
kairos-tx/src/lib.rs

This PR adds support for `no_std` in `kairos-tx` :rocket:.
**Note:** I replaced `thiserror` with plain enum implementing `fmt::Display`, as advised by @Avi-D-coder :clap:.
Closes #60.

Add `no_std` support to `kairos-tx`

---

flake.lock
flake.nix
kairos-contracts/demo-contract-tests/tests/integration_tests.rs

The pipeline for [53899b1](https://github.com/cspr-rad/kairos/pull/69/commits/53899b17aa17acab4a45e7d1c1ed147a5e4fa945) should fail ([see pipeline error](https://hercules-ci.com/accounts/github/cspr-rad/derivations/%2Fnix%2Fstore%2Fvydscd7a14b82l99ksg9gln44mipwi8q-kairos-tarpaulin-0.1.0.drv/log?via-job=a539e130-30d6-4084-9981-a41914c5306b))
After updating to tarpaulin 0.28 (see [release notes](https://github.com/xd009642/tarpaulin/releases/tag/0.28.0), which is achieved by updating nixpkgs, this flag is not required anymore (see [succeeding build](https://hercules-ci.com/accounts/github/cspr-rad/derivations/%2Fnix%2Fstore%2Fhnfhz9zx8xkd2jzc9n9w80y21z1mczcm-kairos-tarpaulin-0.1.0.drv?via-job=763a17b9-022e-4e61-ac16-573abee52f1f))

flake/coverage: remove -Cstrip=none rust flag

---

flake.nix

This PR introduces a more explicit source filtering for the kairos-node related workspace.
We currently have 3 workspaces in this monorepo, this has 2 reasons:
- the risc0 toolchain is different from the one we need for kairos and it is quite big. We do not want to rebuild risc0 in every nix build when a source changes
- nix wants clear separation of host and target platforms for cross-compilation
Since the other two workspaces are located in `kairos-prover` and `kairos-contracts`, and both of them are a subdirectory of the `kairos` workspace, and we say `src = ./.` with nix for the `kairos` workspace, any change of sources which are not related to `kairos`, will trigger a nix rebuild, since the changed sources cause the hash of the derivation to change.
with source filtering we can avoid …

flake: explicit source filtering

---

Cargo.toml
flake.nix
kairos-test-utils/Cargo.toml
kairos-test-utils/src/cctl.rs

Currently `cargo test` needs to be run inside `nix develop`
Currently we are including integration tests by default when running `cargo test`.
`cctl::tests::test_cctl_network_starts_and_terminates` already takes a very long time.
As we integrate risc0 running all tests will become increasingly untenable.
We should define a default set of fast tests, without `risc0` or `cctl`.
In this pr I add that for only `test_cctl_network_starts_and_terminates`.
When adding slow tests please place them behind a feature and add that feature to `all-tests`
```toml
[features]
all-tests = ["cctl-tests"]
cctl-tests = []
```

Test feature sets

---

Cargo.lock
kairos-test-utils/Cargo.toml
kairos-test-utils/src/kairos.rs

- What the description says.
#92 
Motivation is that we need this when testing the CLI, and this resolves a chicken-and-egg problem with the kairos-server cli

kairos-test-utils/kairos: refactor to use kairos_server::run instead of binary

---

Cargo.lock
kairos-cli/Cargo.toml
kairos-cli/bin/main.rs
kairos-cli/src/client.rs
kairos-cli/src/commands/deposit.rs
kairos-cli/src/commands/mod.rs
kairos-cli/src/error.rs
kairos-cli/src/lib.rs
kairos-cli/tests/cli_tests.rs
kairos-server/src/lib.rs
nixos/tests/end-to-end.nix

- Moved all code except cli parsing to `kairos_cli::run`
- Introduced new `kairos-server-address` option, that defaults a value if not set
- Implemented a client function that will submit a transaction to the `kairos-server`, this client function introduces a `KairosClientError` enum type that could be used for better error handling
- implemented the mapping from cli arguments for a deposit -> deposit payload, signing and submitting of a deposit
- Updated the integration test to actually spawn a kairos-server
- Updated the ne2e-test
#92 
-

kairos-cli: implement call to deposit endpoint and integration test

---

Cargo.lock
demo-contract-tests/Cargo.toml
demo-contract-tests/tests/integration_tests.rs
demo-contract-tests/tests/test_fixture/mod.rs
demo-contract-tests/tests/test_fixture/wasm_helper.rs
flake.nix
kairos-contracts/Cargo.lock
kairos-contracts/demo-contract/contract/Cargo.toml
kairos-contracts/demo-contract/contract/src/constants.rs
kairos-contracts/demo-contract/contract/src/main.rs
kairos-contracts/demo-contract/contract/src/utils.rs
kairos-contracts/demo-contract/deposit-session/Cargo.toml
kairos-contracts/demo-contract/deposit-session/src/main.rs
kairos-contracts/demo-contract/malicious-reader/Cargo.toml
kairos-contracts/demo-contract/malicious-reader/src/main.rs
kairos-contracts/demo-contract/malicious-session/Cargo.toml
kairos-contracts/demo-contract/malicious-session/src/main.rs
kairos-test-utils/Cargo.toml

Final suggestions before merging **demo contract**.
- b17471f - Remove unused `base64` dependency.
- 9ec324f - Remove unused `test-support` feature from contract dependency.
- 8d648e4 - Remove unused `bincode` dependency and use `no-std-helpers`.
- 0709c3e - Switch to Casper dependencies from crates.
- 8cf3bc5 - Disable default features where possible.
- 46b1fc4 - Unify format of `Cargo.toml` files.
- 8440fa4 - Remove outdated comment about security badges.
- 757c612 - Fix misplaced args with contract package/uref.
- 25a70d1 - Simplify comment about contract utilities.
- 4bcb72e - Avoid using "deposit contract" name.
- 8010d8e - Stored contract name is actually a contract hash.
_No longer need to set `PATH_TO_WASM_BINARIES`, install `wasm-opt` or use Nix :face_exhaling:. Just compile …

Final demo contract suggestions

---

.github/workflows/check.yml

https://github.com/cspr-rad/kairos/commit/44a7c6e76083e86c1f893ada94e6c2b9d1fb2ab1
Revert removed running the ci when a PR is opened to main

ci: revert removing of check run when PR opened to main #44a7c6e

---

flake.nix
kairos-contracts/Cargo.lock
kairos-contracts/demo-contract/contract/Cargo.toml
kairos-contracts/demo-contract/contract/src/main.rs
kairos-contracts/demo-contract/deposit-session/Cargo.toml
kairos-contracts/demo-contract/deposit-session/src/main.rs
kairos-contracts/demo-contract/malicious-reader/Cargo.toml
kairos-contracts/demo-contract/malicious-reader/src/main.rs
kairos-contracts/demo-contract/malicious-session/Cargo.toml
kairos-contracts/demo-contract/malicious-session/src/main.rs
kairos-contracts/rust-toolchain.toml

I extracted `no_std` helpers from `casper-contract` and made it available for stable Rust:
- https://github.com/koxu1996/casper-contract-no-std-helpers/tree/master
Closes #117.

Build contracts with stable toolchain

---

Cargo.lock
kairos-prover/Cargo.lock
kairos-tx/Cargo.toml

`kairos-tx` is mainly based on `rasn`, ASN.1 library that claims to be `no_std`:
I recently discovered that it implicitly pulls `std` in 3 different ways - described in https://github.com/librasn/rasn/issues/262.
Until it's fixed, I am proposing to use my fork - [see changes here](https://github.com/librasn/rasn/compare/main...koxu1996:rasn:feature/real-no-std-compatibility).
With this PR we get full `no_std` compatibility, proved with:
```
$ rustup target add thumbv7m-none-eabi
$ cargo build -p kairos-tx --no-default-features --target thumbv7m-none-eabi
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.08s
```

Use `rasn` fork that is fully compatible with no-std

---

Cargo.lock
flake.nix
kairos-cli/Cargo.toml
kairos-cli/src/commands/transfer.rs
kairos-cli/src/commands/withdraw.rs
kairos-crypto/Cargo.toml
kairos-crypto/src/error.rs
kairos-crypto/src/implementations/casper.rs
kairos-crypto/src/lib.rs

This PR moves feature-gated parts of `trait CryptoSigner` into separate traits:
- filesystem extension - https://github.com/cspr-rad/kairos/pull/123/commits/8027d711ddda532892550bfe4c5a44f09f229f65
- transaction extension - https://github.com/cspr-rad/kairos/pull/123/commits/a0950699ec75a4b1ac865cf4b6713b8d88e0e11f
Additionally `no_std` support is introduced - https://github.com/cspr-rad/kairos/pull/123/commits/4684d4fdb2c066179cc6008aba1f56e2d02d8a10.
Closes #86.

`kairos-crypto` - split trait and introduce `no_std` support

---

Cargo.lock
kairos-contracts/Cargo.lock
kairos-contracts/demo-contract/contract-utils/Cargo.toml
kairos-contracts/demo-contract/contract/src/main.rs

`u64` is not compatible with the casper-event-standard: https://github.com/make-software/casper-event-standard/blob/ad942762a099fc29c0df4cbd3604da8201704195/casper-event-standard/src/contract.rs#L21
We us the last_processed_deposit_index for our deposit window, and we could end up with a much bigger index there than the events length

Fixup deposit counter type

---

demo-contract-tests/tests/test_fixture/mod.rs
flake.nix
kairos-contracts/Cargo.toml

In Casper v1.5.6 [maximum contract size](https://github.com/casper-network/casper-protocol-release/blob/ce0c03e4b90a2abc0066a2dc13da38d667381423/config/chainspec.toml#L133-L134) is 1 MiB (1,048,576 bytes), which we fairly exceed with demo contract (1.4 MiB), therefore making Kairos incompatible with production network.
I was suspecting that Risc0 verifier might be the biggest part of final WASM, so I did some tests on [bare minimum contract](https://gist.github.com/koxu1996/9a01db96c632b41268ed0138dd75d01f). However, bare Risc0 verifier (+ bincode2 deserialization for receipt) is less than 20 KB :space_invader:. Casper API calls are also quite small (few kilobytes), so it means we should be able to get way less than 1 MiB.
Simple idea: we can enable more aggressive optimization in Rust …

Reduce WASM size to fit into production chainspec

---

kairos-cli/src/client.rs
kairos-cli/src/commands/deposit.rs
kairos-cli/src/common/args.rs
kairos-server/src/lib.rs
kairos-server/src/routes/get_chain_name.rs
kairos-server/src/routes/mod.rs

This PR fixes #155.
1. Added simple endpoint to Kairos server, that returns chain name:
```
$ curl 127.0.0.1:9999/api/v1/chain_name
"casper-net-1"
```
2. Introduced **optional** `--chain_name` argument for CLI's deposit:
```
$ kairos-cli deposit --help | grep chain
--chain-name <NAME>              Name of the chain, to avoid the deploy from being accidentally included in a different chain
```
**NOTE:** Help text is based on `casper-client`.
In case chain name is not provided, CLI will query server for it.

Dehardcode chain name in CLI

---

kairos-cli/src/commands/run_cctl.rs
kairos-test-utils/src/cctl.rs
kairos-test-utils/tests/test_cctl_deploys_a_contract_successfully.rs
kairos-test-utils/tests/test_cctl_network_starts_and_terminates.rs

There is no need to make those env required during compile time. It will help with #171.

Move compile-time `CCTL_CHAINSPEC` and `CCTL_CONFIG` to runtime

---

flake.nix
kairos-server/src/routes/get_chain_name.rs
kairos-server/src/state/submit_batch.rs

This PR gets rid of `CASPER_CHAIN_NAME` env variable - it gets fetched dynamically from RPC. In the future we could introduce cache for it.

Dynamic chainname fetch
